language: php
php:
  - nightly
  - hhvm
  - 7.0
  - 5.6

matrix:
  allow_failures:
    - php: nightly

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls -v
