language: php
php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls -v
