language: php

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
  include:
    - php: 5.6
      env: PHPUNIT_VERSION="5.7.*"
      script: ./scripts/phpunit-with-coveralls.sh
    - php: 7.0
      env: PHPUNIT_VERSION="6.1.*"
    - php: hhvm
      env: PHPUNIT_VERSION="6.1.*"
    - php: nightly
      env: PHPUNIT_VERSION="6.1.*"

before_install:
  - composer self-update
  - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update

install: composer update --no-interaction --prefer-source
