language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  - PHPUNIT_VERSION="5.2.*"

matrix:
  allow_failures:
    - php: 7.0
    - php: nightly
  include:
    - php: 5.2
      env: PHPUNIT_VERSION="3.7.0"
    - php: 5.3
      env: PHPUNIT_VERSION="4.8.*"
    - php: 5.4
      env: PHPUNIT_VERSION="4.8.*"
    - php: 5.5
      env: PHPUNIT_VERSION="4.8.*"

before_install:
  - travis_retry composer self-update
  - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update

install: composer update --no-interaction --prefer-source
